Feat/7 build alarm clock view UI
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #15
Opened 2022-07-19 02:55 UTC by tea-hkim

## 👀 관련 이슈

Closes #7 
## 👀 구현/변경 사항

### AlarmClockViewController 시계 그리기
- AlarmClockView 타이틀 배치
- 1분 마다 시간이 지나도록 구현 - 관련 함수(`setTime()`)
- 시간에 따라 오전, 오후 바뀌도록 구현 - 관련 함수(`setTime()`)
- 그라데이션 원 가운데 배치 - 관련 함수(`drawGradientCircle()`)

### AlarmClockViewController 5분 뒤 알림/ 종료 버튼 그리기
- 버튼 스택 뷰 내부에 배치
- CornerStyle을 large로 지정 (이 부분 버튼의 cornerRadius를 설정하지 않고 스토리 보드에 있는 기본 설정을 활용했습니다)

## 👀 PR Point

viewDidLoad에 쓰여있던 코드들이 가독성이 떨어진다는 의견이 있어서
시간을 세팅하기 위한 함수와 그라데이션 원을 그리기 위한 함수를 만들었습니다. 

```Swift
private func setTime(){
    let date = Date()

    let dateFormatter = DateFormatter()
    let ampmFormatter = DateFormatter()

    dateFormatter.dateFormat = "hh: mm"
    ampmFormatter.dateFormat = "a"

    let currentTime = dateFormatter.string(from: date)
    let ampmSetter = ampmFormatter.string(from: date)

    self.timeLabel.text = currentTime
    self.ampmLabel.text = ampmSetter
  }
```

```Swift
private func drawGradientCircle() {
    let lineWidth: CGFloat = 3
    let originOffset: CGFloat = lineWidth
    let circleDiameter: CGFloat = 278

    let gradient = CAGradientLayer()

    gradient.frame =  CGRect(origin: CGPoint(x: 0, y:  0),
                             size: morningCircle.frame.size)
    gradient.colors = [UIColor.white.cgColor, UIColor.systemOrange.cgColor]

    let rectangle = CGRect(origin: CGPoint(x: originOffset, y: originOffset),
                           size: CGSize(width: circleDiameter - lineWidth*2,
                                        height: circleDiameter - lineWidth*2))

    let shape = CAShapeLayer()
    shape.lineWidth = lineWidth
    shape.path = UIBezierPath(ovalIn: rectangle).cgPath
    shape.strokeColor = UIColor.black.cgColor
    shape.fillColor = UIColor.clear.cgColor
    gradient.mask = shape
    morningCircle.layer.addSublayer(gradient)
  }
```

## 👀 참고 사항

<image src = "https://user-images.githubusercontent.com/81206228/179654245-d4883fc9-dd01-4f1f-8060-a9f1b3fcf88b.png" width="250" height="600">

2022-07-19 13:37 UTC, taehyeonk reviewed
멋져요..!
결국 지름 사이즈 278 고정으로 구현한게 맞나요?

2022-07-19 13:37 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    dateFormatter.dateFormat = "hh: mm"
시간 표시 .dataFormat이 표시하는 형식을 지정한다고 이해했는데
시간과 분 사이에 공백 동일하게 한 칸씩 주지 않고 "hh: mm"인 의도가 있는 걸까요??

2022-07-19 13:45 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    dateFormatter.dateFormat = "hh: mm"
아 타자를 빠르게 치다보니 오타가 났습니다. 수정하겠습니다 :)
원의 지름은 결국 278로 고정되었습니다.
아이폰 se 3세대까지 확인한 결과 동일한 원의 지름을 가지고 있고 가운데에 제대로 배치 되는 것을 확인했습니다 😄

2022-07-20 00:44 UTC, chaneeii requested changes

2022-07-20 00:44 UTC, chaneeii commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var ampmLabel: UILabel!
p1

추후 모델 및 다른 페이지와의 코드 통일성, 언어적 의미 측면에서 
ampmLabel -> `meridiemLabel` 로 바꿨으면 합니다!

다른 분들 코드 리뷰하면서 제가 요건 meridiem 으로 통일하고 다니겠습니다. 🥳

2022-07-20 00:44 UTC, chaneeii commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +
일반적으로 날짜관련 함수는 util 로 따로 빼둡니다!
근데 저희 모델이 아직 나오지 않아 아마 추후 수정이 필요할것같아 우선은 그냥 두는 걸로 하고 나중에 이부분 리팩토링 하는 걸로 하는건 어떨까요?

p1
ampm -> meridiem 로 수정바랍니다.

2022-07-20 00:44 UTC, chaneeii commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var morningCircle: UIView!
morningCircle 이라는 표현이 오전에만 쓰는 원이라고 느껴져서 다른 작명이 있으면 좋을 것 같습니다..!

wakeupTimeCircle (기상시간알림 원) 은 어떨까요.....? 😶‍🌫️ 변수명짓기는 언제나 어렵네요ㅠ

2022-07-20 01:00 UTC, jinccc97 approved these changes

2022-07-20 01:00 UTC, jinccc97 commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var morningCircle: UIView!
에이버리 의견에 동의합니다!

2022-07-20 01:06 UTC, compuTasha approved these changes
그라데이션 들어간 중간 원까지..!
디자인 그대로 구현해주셨군요 👍👍
편-안 합니다

2022-07-20 01:06 UTC, compuTasha commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmClockView;
p2;

이 부분 다시 Main 으로 돌려두고 커밋해야 할 것 같습니다..!
(사진에 Main Interface 를 수정하면 되는 것 같아요)
<img width="887" alt="image" src="https://user-images.githubusercontent.com/51108729/179870326-71c10b6f-aa13-4117-a60d-9514694d00e9.png">

2022-07-20 01:06 UTC, compuTasha commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    }
p4;

이 코드를 
`Timer.scheduledTimer(withTimeInterval: 1, target: self, selector: #selector(setTime), repeats: true)`
이렇게 대체할 수 있을까요??
(_) in self.setTime()이 같은 의미인 것 같아서 여쭤봅니다

2022-07-20 01:17 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var ampmLabel: UILabel!
오 어떻게 표현해야 할 지 몰라서 고민하고 있었는데 바로 수정하겠습니다

2022-07-20 01:20 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +
util이라는게 utility를 의미하는 건가요??
어떻게 사용하는지 예시를 보여주실 수 있나요?
어떤 키워드로 찾아야 하는지 몰라서 ㅠㅠ
https://kkh0977.tistory.com/1654 이 블로그에서 나온 것 처럼 사용하면 되는 것인지 궁금합니다!

2022-07-20 01:21 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var morningCircle: UIView!
아하 아침 해를 모티브로 만들었다고 생각해서 그 점은 생각을 못했습니다! 수정하겠습니다

2022-07-20 01:23 UTC, tea-hkim commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmClockView;
아 info.plist만 생각하고 프로젝트 파일을 돌려놓는 건 생각을 못했네요 ㅠ 수정해서 push 하겠습니다

2022-07-20 01:23 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    }
아 제가 Timer에 대한 제대로 된 이해를 하지 않고 무작정 코드를 사용해서 다시 살펴보고 수정하겠습니다 !

2022-07-20 02:06 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    }
수정했습니다! 확인해본 결과 타이머가 바로 실행되는 것은 아니라서 함수를 먼저 실행해주는 것은 불가피 할 것 같습니다 😢

2022-07-20 02:29 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var morningCircle: UIView!
수정했습니다! (https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/ecdf29b04c9487cd3a40749c99fef05d4ec6a55e)

2022-07-20 02:29 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +  @IBOutlet weak var ampmLabel: UILabel!
수정했습니다! (https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/ecdf29b04c9487cd3a40749c99fef05d4ec6a55e)

2022-07-20 02:29 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    dateFormatter.dateFormat = "hh: mm"
수정했습니다! (https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/ecdf29b04c9487cd3a40749c99fef05d4ec6a55e)

2022-07-20 03:37 UTC, taehyeonk approved these changes

2022-07-20 04:58 UTC, pppaper approved these changes
코드 정말 멋져요~!!! 앞으로도 파이팅 😎👍

2022-07-21 00:56 UTC, compuTasha commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +
@chaneeii

2022-07-21 01:15 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +
> p1
> ampm -> meridiem 로 수정바랍니다.

수정했습니다! (https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/ecdf29b04c9487cd3a40749c99fef05d4ec6a55e)

2022-07-21 01:26 UTC, chaneeii approved these changes

2022-07-21 01:27 UTC, merged

2022-07-21 09:47 UTC, compuTasha commented on Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
> +    }
악 아쉽네요..ㅠㅠ 고생하셨습니다!!