✨ feat : 수면기록화면 UI 구성
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #16
Opened 2022-07-19 03:19 UTC by jinccc97

## 👀 관련 이슈
#10 

## 👀 구현/변경 사항
수면 기록 화면의 테이블뷰를 구현했습니다.

## 👀 PR Point

## 👀 참고 사항
상단의 + (add) 버튼은 빈화면에서 테이블이 추가된 화면이 잘 나타나는지 확인을 위한 버튼입니다! 추후 삭제 예정입니다.
![Simulator Screen Shot - iPhone 13 - 2022-07-19 at 12 17 44](https://user-images.githubusercontent.com/61951603/179657130-27937963-50ad-4eff-9370-b040325ead89.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-19 at 12 17 48](https://user-images.githubusercontent.com/61951603/179657135-d3cb43be-fd5d-403b-a6d8-3fe3d88fbb00.png)

2022-07-19 14:20 UTC, taehyeonk reviewed
코드 스타일 가이드 지키는거 너무 어려운거 같아요..
테이블 완전 깔끔하게 잘나오네요!👍👍👍

2022-07-20 00:49 UTC, chaneeii approved these changes
🥳 고생많았습니다!
PR 보낼때 스크릿샷 사이즈가 커서 밑에 커멘트랑 리뷰가 잘안보일수있는데 아래 내용 한번 참고해보세요!

[[Tip] PR 보낼때 스크린샷 이미지 조절하는 법 #10](https://github.com/DeveloperAcademy-POSTECH/MC2-Team16-Trit/issues/10#issue-1260663137)

2022-07-20 00:49 UTC, chaneeii commented on Inception/Inception/Screens/SleepTracker/DailySleepTrack.swift
> +
오! 밀리 이미 짜둔 모델이 있었네요! 
요부분은 제가 모델짤때 반영해서 넣어보겠습니다!

2022-07-20 00:58 UTC, tea-hkim approved these changes
코드가 깔끔하게 잘 정리되어있네요!

2022-07-20 00:58 UTC, tea-hkim commented on Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
> +    // Initialization code
스타일쉐어 Swift 한국어 가이드에 따르면 이런 주석을 사용할 때는 문서화를 위해 ///를 쓰도록 권장하고 있습니다! :)

2022-07-20 00:58 UTC, tea-hkim commented on Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
> +    super.awakeFromNib()
이 부분은 어떤 코드인가요?? 왜 사용되었는지 궁금합니다!

2022-07-20 00:58 UTC, tea-hkim commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +      tableView.isScrollEnabled = false
이 코드를 통해 스크롤 가능 여부를 꼭 지정해줘야 하는건가요??
높이에 따라 스크롤 가능 여부가  자동으로 설정 가능할 것 같은데

2022-07-20 01:00 UTC, jinccc97 commented
> 
감사합니다! 확인 후 수정하겠습니다!

2022-07-20 01:01 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
> +    // Initialization code
오 안그래도 주석을 찾아봤는데 제대로 안찾아봤었군요...
감사합니다! 수정하겠습니다!

2022-07-20 01:10 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +      tableView.isScrollEnabled = false
넹 ㅠ 따로 지정해주지 않았더니 테이블에 아무것도 없는데도 스크롤 액션이 진행되어 부자연스럽더라구요

2022-07-20 01:10 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
> +    super.awakeFromNib()
UItableView 파일을 만들 때 자동으로 채워져있는 함수라서 저도 있는 줄 몰랐네요..!
 찾아보니 UIView의 frame등을 처음에 세팅하는 함수인 듯 합니다.
  저는 크게 필요하지 않을 듯하여 지우도록 하겠습니다!

2022-07-20 01:10 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/DailySleepTrack.swift
> +
감사합니다! 에이버리 짱!

2022-07-20 01:30 UTC, compuTasha requested changes
테이블 헤더들 혼쭐내느라 수고하셨습니다..👍👍

2022-07-20 01:30 UTC, compuTasha commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = SleepTrackerStoryboard;
p2;

이 부분 다시 Main 으로 돌려두고 커밋해야 할 것 같습니다..!
(사진에 Main Interface 를 수정하면 되는 것 같아요)
<img width="887" alt="image" src="https://user-images.githubusercontent.com/51108729/179870326-71c10b6f-aa13-4117-a60d-9514694d00e9.png">

2022-07-20 01:30 UTC, compuTasha commented on Inception/Inception/Info.plist
> +					<string>SleepTrackerStoryboard</string>
p2;

변경된 Info.plist 파일은 풀리퀘에서 제외해주세요!

2022-07-20 01:30 UTC, compuTasha commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIUserInterfaceStyle = Dark;
오홍 다크모드만 지원하도록 변경한건가요?!

2022-07-20 01:30 UTC, compuTasha commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +  // 여기까지 삭제
저희 이번에 '수면 기록 셀프 수정/ 추가'가 빠져서
이 부분은 고려 안 해도 될 것 같아요..!

2022-07-20 01:30 UTC, compuTasha commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +    }
p2;

데이터가 있는 경우에 대해서는
이 코드들이 테이블뷰의 기본값이라
따로 예외 처리를 안 해도 될 것 같아요!

= 데이터가 없는 경우만 예외 처리를 하면 될 것 같습니다

2022-07-20 01:31 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +    }
수정했습니다!

2022-07-20 01:31 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +  // 여기까지 삭제
아 이부분은 셀프 수정 그 기능을 위해서가 아닌 순수한 empty 화면 테스트를 위한 버튼입니다!

2022-07-20 01:41 UTC, jinccc97 commented on Inception/Inception/Info.plist
> +					<string>SleepTrackerStoryboard</string>
8459d8a5ba95d1643bc7f707b065ab36032136a1
수정했습니다!

2022-07-20 01:42 UTC, jinccc97 commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = SleepTrackerStoryboard;
8459d8a5ba95d1643bc7f707b065ab36032136a1 수정했습니다!

2022-07-20 02:09 UTC, compuTasha approved these changes

2022-07-20 02:45 UTC, pppaper reviewed
밀리 정말 멋집니다! 고생하셨어요👍

2022-07-20 03:40 UTC, taehyeonk approved these changes

2022-07-20 03:43 UTC, merged