Feat/1 layout global
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #17
Opened 2022-07-19 03:41 UTC by pppaper

## 👀 관련 이슈

#1 

## 👀 구현/변경 사항

알람 계산 화면에 세그먼트 컨트롤과 네비게이션 타이틀을 만들었습니다.

## 👀 PR Point

아주 짧고 간단한 내용입니다.

## 👀 참고 사항

세그먼트 컨트롤에 firstView와 secondView가 약간 꼬였을 수도 있습니다..
![Simulator Screen Shot - iPhone 13 - 2022-07-19 at 12 40 39](https://user-images.githubusercontent.com/103012106/179659681-7a5c4d6f-8558-4646-9799-54a6cf6334cc.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-19 at 12 40 42](https://user-images.githubusercontent.com/103012106/179659684-93d05150-a9d2-4273-97be-e1e28f82a53e.png)

2022-07-19 14:27 UTC, taehyeonk reviewed
기능 구현 깔끔했다..!👍👍

2022-07-20 00:45 UTC, taehyeonk reviewed
File changed에 xcsheme 파일과 Base.Iproj 폴더 내에 Main.storyboard, 그리고 Info.plist 변경사항을 지우고 다시 PullRequest 할 수 있을까요??

Github에서 해당사항 Discard하는 방법을 아시는 분이 있을까요?? 너울 브랜치에서 시작해서 제 PullRequest에서도 그대로 있습니다..ㅠㅠ
@pppaper @compuTasha @tea-hkim @chaneeii @jinccc97

2022-07-20 00:58 UTC, chaneeii requested changes
고생하셨습니🥳 변경요청사항 반영부탁드립니다

PR 보낼때 스크릿샷 사이즈가 커서 밑에 커멘트랑 리뷰가 잘안보일수있는데 아래 내용 한번 참고해보세요!

[[Tip] PR 보낼때 스크린샷 이미지 조절하는 법 #10](https://github.com/DeveloperAcademy-POSTECH/MC2-Team16-Trit/issues/10#issue-1260663137)

2022-07-20 00:58 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
> +  @IBOutlet weak var secondView: UIView!
p1
firstView / secondView 대신 각 화면 기능을 담은 직관적인 이름으로 View 이름을 네이밍 부탁드립니다!
요러한 네이밍은 각 뷰가 어떠한 역할을 하는지 알수없어요ㅠ 
bedTimeSearchView / wakeupTimeSearchView 등의 작명은...어때요? 저도 좋은 작명가는 아닙니다..!

2022-07-20 01:05 UTC, tea-hkim reviewed
main 파일에 변경이 있습니다!!
main이나 info.plist 파일의 경우 공동으로 사용되는 부분인 만큼 변경사항이 생기면 제외하고 올려주시면 좋을 것 같아요 :)

2022-07-20 03:11 UTC, pppaper commented
> main 파일에 변경이 있습니다!! main이나 info.plist 파일의 경우 공동으로 사용되는 부분인 만큼 변경사항이 생기면 제외하고 올려주시면 좋을 것 같아요 :)

말씀해주신 사항 변경해서 커밋했습니다!

2022-07-20 03:44 UTC, taehyeonk approved these changes

2022-07-20 03:46 UTC, taehyeonk requested changes
Segmented Control로 보여지는 2페이지 구분을 위해서 배경색을 넣어놓은 것 같아요!
정상 동작한다면 검은 배경으로 변경후 다시 PR 해주시면 좋을 듯 합니다.

2022-07-20 03:54 UTC, pppaper commented
> Segmented Control로 보여지는 2페이지 구분을 위해서 배경색을 넣어놓은 것 같아요! 정상 동작한다면 검은 배경으로 변경후 다시 PR 해주시면 좋을 듯 합니다.

[7fc36a3](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/pull/17/commits/7fc36a3d0d9687cda3a59cefc0afc37570cdaa2e) 배경화면 검정색으로 변경했습니다!

2022-07-20 04:43 UTC, pppaper commented on Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
> +  @IBOutlet weak var secondView: UIView!
이름 변경 시도를 몇 번 했는데, 코드에서는 바로 바뀌는데 스토리보드에서는 잘 안 바뀌어서 쉽지가 않네요ㅠㅠ 변경하는데 시간이 좀 걸릴 것 같습니다...ㅜㅜ

2022-07-20 04:53 UTC, pppaper commented
> 고생하셨습니🥳 변경요청사항 반영부탁드립니다
> 
> PR 보낼때 스크릿샷 사이즈가 커서 밑에 커멘트랑 리뷰가 잘안보일수있는데 아래 내용 한번 참고해보세요!
> 
> [[Tip] PR 보낼때 스크린샷 이미지 조절하는 법 #10](https://github.com/DeveloperAcademy-POSTECH/MC2-Team16-Trit/issues/10#issue-1260663137)

이미지가 커서 한눈에 보기 불편했는데 덕분에 잘 수정했어요!! 감사합니다👍

2022-07-20 14:58 UTC, taehyeonk approved these changes

2022-07-21 01:04 UTC, compuTasha approved these changes
수고하셨습니다!!✨✨👍

2022-07-21 01:25 UTC, kangeunbidesign commented on Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
> +  @IBOutlet weak var secondView: UIView!
[2e8aa0b](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/pull/17/commits/2e8aa0bb1a614f5084447084dbe032cd314bebf7)
bedTimeBasedView
wakeupTimeBasedView
로 변경했습니다! @chaneeii

2022-07-21 01:48 UTC, chaneeii approved these changes
🥳🥳🥳

2022-07-21 02:01 UTC, merged