Feat/11 alarm calc cell layout
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #19
Opened 2022-07-19 13:17 UTC by taehyeonk

## 👀 관련 이슈
- #1 
- #11 

## 👀 구현/변경 사항
- 기존 [#1] 에서 작성한 Segmented controls로 이동하는 뷰 내에서 UITableView로 Custom Cell 구현
  - Sketch 기준에서 여백이 맞지 않아서 기상 시간 기준 Cell과 취침 시간 기준 Cell 글자 및 여백 통일
  - Xib 파일로 나누어서 Custom Cell만 따로 구현

## 👀 PR Point
- UITableViewCell에 Storyboard에서 만든 요소들을 다 연결하고, 
``` swift
// SleepBasedRecoCell.swift
class SleepBasedRecoCell: UITableViewCell {
  @IBOutlet weak var sleepIcon: UIImageView!
  @IBOutlet weak var sleepCycle: UILabel!
  @IBOutlet weak var sleepLabel: UILabel!
  @IBOutlet weak var awakeLabel: UILabel!
  @IBOutlet weak var sleepTime: UILabel!
  @IBOutlet weak var awakeTime: UILabel!
  @IBOutlet weak var addButton: UIButton!

  ...
}
```
- UITableViewDataSource 와 UITableViewDelegate를 상속하는 UIViewController에서 각 cell에 들어갈 값을 넣어주는 방식으로 구현
``` swift
// SleepBasedViewController.swift
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    ...

    // Cell Label의 내용 지정
    cell.sleepIcon.image = UIImage(systemName: "bed.double.fill")?.withTintColor(
      .systemOrange,
      renderingMode: .alwaysOriginal
    )
    cell.sleepCycle.text = data[indexPath.row].sleepCycle
    cell.sleepLabel.text = "취침"
    cell.awakeLabel.text = "기상"
    cell.sleepTime.text = data[indexPath.row].sleepTime
    cell.awakeTime.text = data[indexPath.row].awakeTime

    // 생성한 Cell 리턴
    return cell
  }
```

- 오토 레이아웃으로 Custom Cell을 만들 때, 좌측 요소 중 취침을 가운데 요소로 두고 위아래 요소간 간격을 줘서 요소들이 셀의 중앙에 배치되게 하려고 했을 때, 전체 Cell 높이와 맞지 않아서 깨지는 문제를 옆에 추천 버튼 하나에만 위아래 간격을 동일하게 주면서 문제 해결
  - 좌측 요소들은 오토레이아웃이 깨지지 않게 위아래 여백을 주지 않음
<p align="center"><img width="400" alt="image" src="https://user-images.githubusercontent.com/29690062/179756438-db8abf0a-ec61-46e0-a2da-7e35c906fd1e.png"></p>

## 👀 참고 사항
UITableView에서 Custom Cell 구현 시 참고했던 페이지 링크
- [iOS :: TableView Storyboard로 구현하기](https://shark-sea.kr/entry/iOS-TableView-Storyboard%EB%A1%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
- [UITableView 와 Custom UITableViewCell 적용 하기 | Swift](https://intrepidgeeks.com/tutorial/apply-uitableview-and-custom-uitableviewcell-swift)
- [TableViwe 만들기(Custom Cell을 만들어 보기)](https://karzin.tistory.com/210)
Cell 선택시 이벤트 구현 시 참고할 링크
- [[iOS] Tableview 만들기 ( Custom Tableview Cell )](https://superwony.tistory.com/186)
Storyboard를 사용하지 않고 코드로 구현할 시 참고할만한 링크
- [iOS) UITableView 스토리보드 없이 코드 작성(programmatically)](https://feelsodev.tistory.com/6?category=800253)

2022-07-20 01:09 UTC, chaneeii requested changes
고생한게 느껴지는 코드였습니다! 수고하셨습니다~!🥳🥳

변경사항 몇개만 반영 부탁드릴게요!

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
> +  @IBAction func switchViews(_ sender: UISegmentedControl) {
요부분 네이밍이 별로라 너울쪽에 변경요청드렸는데 나중에 merge 할때 너울쪽으로 가져가면 좋을 것 같습니다~

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +    cell.awakeTime.text = data[indexPath.row].awakeTime
p2
요 부분을 AwakeBasedRecoCell 에 func 으로 파서 한번에 정리하는 것이 좋을 것 같아요!
저도 추가 반영하면 좋을 것 같네요
밀리 코드 참고해보면 좋을 것 같습니다!

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
p3

밀리랑 제쪽에서는 단어 선택이 비슷한데 이쪽에서 달라서 나중에 헷갈리는 부분이 있을 것 같아요! 아래스타일로 변경하는거 어떨까요?

취침시간 : bedTime
기상시간 : wakeupTime

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
p3
마찬가지로 네이밍 관련 제안드립니다

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/Cell/TimeDataModel.swift
> +  var sleepCycle: String
sleepCycle : 수면주기 라는 뜻인데 아래 사용하는 예시를 보니 sleepHour : 수면시간 내용이라 sleepHour 로 관련 내용 수정 부탁드립니다

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +  // 한 섹션(구분)에 몇 개의 셀을 표시할지
p1 
요러한 주석은 커밋할때 날려주셔도 될것 같습니다

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    // 내가 정의한 Cell 만들기
p1
요러한 주석은 커밋할때 날려주셔도 될것 같습니다

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    // Xib로 분할한 Cell 파일 연결을 위한 작업
p1
요러한 주석은 커밋할때 날려주셔도 될것 같습니다

2022-07-20 01:09 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    cell.awakeTime.text = data[indexPath.row].awakeTime
p2 
요기도 함수로 빼면 깔끔할 것 같아요!

2022-07-20 01:17 UTC, tea-hkim approved these changes
코드가 주석 처리를 통해 깔끔하게 정리가 되어있어서 읽기 편했습니다!

2022-07-20 01:17 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  // 한 섹션(구분)에 몇 개의 셀을 표시할지
p3
스타일쉐어 가이드에서는 주석의 경우 문서화를 위해 ///를 사용하도록 권장하고 있습니다!
코드에 주석을 달아 섹션을 나눠주셔서 읽기 편합니다 👍

2022-07-20 01:17 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
p4
원래 storyboard 작업을 할 때 바뀌지 않는 요소들도 모두 viewController와 연결을 해야하는건가요??
어떻게 해야하는 지 몰라서 물어봤습니다!

2022-07-20 01:17 UTC, tea-hkim commented on Inception/Inception/Screens/AlarmCalculator/Cell/TimeDataModel.swift
> +  init(sleepCycle: String, sleepTime: String, awakeTime: String){
p4

struct의 경우 생성자를 입력하지 않으면 자동으로 생성자를 만들어 초기화 할 수 있도록 해줍니다!

2022-07-20 05:10 UTC, pppaper approved these changes
넘 멋집니다!! 고생하셨습니다 👍

2022-07-20 13:13 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
저도 뭔가 스토리보드에서 고정할 수 있는 뭔가가 없나 했는데, 스토리보드에서 Label이나 ImageView로 처리하게 되었을 때, 안에 들어가게될 내용을 결국 연결해서 고정 값을 넣어주는 식으로 해결해야되나..? 하고 생각해서 그렇게 처리했습니다. 그러고보니 보드에 바로 고정값을 넣을 수 있는지 고민해보지 않았던 것 같네요

2022-07-20 14:48 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
너무 기본적인 내용이라 찾지 못하고 삽질한거 였네요..
스토리보드를 쓰는 이유가 지정한 값으로 뷰를 볼 수 있어서였군요;;
스토리보드에서 각 요소들 연결하고 값을 넣으면 바뀌길래 무저건 지정해 줘야한다고 착각한 것 같아요. 코드에서 값을 넣지 않으니 그대로 나오는 군요 ㅋㅋㅋㅋㅋ
고정 된 요소들은 스토리보드에서 직접 값을 넣어서 작업해두고 코드에서 변경하는 부분을 삭제하는 걸로 처리했습니다. (8e4cc6c3f7002af381d7430e75779ef7f6114bfa)

2022-07-20 14:48 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/TimeDataModel.swift
> +  init(sleepCycle: String, sleepTime: String, awakeTime: String){
불필요해져서 삭제하는 것으로 처리했습니다. (8e4cc6c3f7002af381d7430e75779ef7f6114bfa)

2022-07-20 14:49 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  // 한 섹션(구분)에 몇 개의 셀을 표시할지
불필요하다고 생각되어 삭제처리 했습니다 (30adad18a7beb950996e0d2b245490e66eb66bc5)

2022-07-20 14:49 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    // Xib로 분할한 Cell 파일 연결을 위한 작업
삭제 처리했습니다 (30adad18a7beb950996e0d2b245490e66eb66bc5)

2022-07-20 14:49 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    // 내가 정의한 Cell 만들기
삭제 처리 했습니다! (30adad18a7beb950996e0d2b245490e66eb66bc5)

2022-07-20 14:50 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +  // 한 섹션(구분)에 몇 개의 셀을 표시할지
삭제 처리했습니다 (30adad18a7beb950996e0d2b245490e66eb66bc5)

2022-07-20 14:52 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
반영해서 변경했습니다 (a579a36e70dbfaa753ad56a7bdfacb03d3365f9f)

2022-07-20 14:52 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +  @IBOutlet weak var addButton: UIButton!
반영해서 변경했습니다 (a579a36e70dbfaa753ad56a7bdfacb03d3365f9f)

2022-07-20 14:53 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/TimeDataModel.swift
> +  var sleepCycle: String
처음에 주기로 얘기했던게 의식의 흐름에 남아서 Cycle로 적었나봐요 ㅋㅋㅋㅋ
생각해보니 그러네요. 변경했습니다 (a579a36e70dbfaa753ad56a7bdfacb03d3365f9f)

2022-07-20 14:54 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
> +  @IBAction func switchViews(_ sender: UISegmentedControl) {
인지하고 충돌 시 너울 변경사항을 가져갈 수 있도록 충돌 해결하겠습니다!!

2022-07-20 14:56 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +    cell.awakeTime.text = data[indexPath.row].awakeTime
덕분에 밀리 코드 잘 참조해서 update 함수로 만들어서 처리했습니다! (8e4cc6c3f7002af381d7430e75779ef7f6114bfa)
@jinccc97

2022-07-20 14:56 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    cell.awakeTime.text = data[indexPath.row].awakeTime
깔끔하게 update 함수 작성해서 수정했습니다 (8e4cc6c3f7002af381d7430e75779ef7f6114bfa)

2022-07-21 01:16 UTC, compuTasha requested changes
수고하셨습니다!!👍👍
커스텀 셀 연결 방법 배워갑니다 총총...

2022-07-21 01:16 UTC, compuTasha commented on Inception/Inception/Info.plist
> +					<string>AlarmCalculator</string>
p2;

Info.plist가 돌아왔어요..!🥲
다시 Main으로 변경 부탁드립니다!

2022-07-21 01:16 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +class AwakeBasedViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
p1;

코드 컨벤션 룰에 따르면 
프로토콜을 적용할 때에는 extension을 만들어서 관련된 메서드를 정리하네요
수정 부탁드립니다..!

```
final class MyViewController: UIViewController {
  // ...
}

// MARK: - UITableViewDataSource

extension MyViewController: UITableViewDataSource {
  // ...
}

// MARK: - UITableViewDelegate

extension MyViewController: UITableViewDelegate {
  // ...
}```

2022-07-21 01:16 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +class AwakeBasedViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
구현된 tableView 함수 둘 다 UITableViewDataSource 프로토콜 하단에 넣으면 될 것 같습니다

2022-07-21 01:23 UTC, chaneeii approved these changes
👏👏👏👏 고생많으셨습니다!

2022-07-21 01:42 UTC, taehyeonk commented on Inception/Inception/Info.plist
> +					<string>AlarmCalculator</string>
앗!!?!?? 언제 들어갔지;; 빠르게 수정했습니다 (f64db8d4fcebf23794c2cf503cb29d6d4b6d0ea3)

2022-07-21 01:43 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +class AwakeBasedViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
수정했습니다! (bc93d3d2f0404099f675e1430dd2bd11cc154c0c)

2022-07-21 01:49 UTC, chaneeii approved these changes
🥳🥳🥳

2022-07-21 02:05 UTC, compuTasha approved these changes

2022-07-21 09:13 UTC, jinccc97 approved these changes
고생많으셨습니다아!

2022-07-21 10:09 UTC, merged