Feat/6 alarm list layout
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #30
Opened 2022-07-21 09:40 UTC by compuTasha

## 👀 관련 이슈

Close #6 

## 👀 구현/변경 사항
- TableView 2개를 활용해 알람 목록을 구현했습니다

## 👀 PR Point
- ScrollView 내부에 2개의 TableView를 구현했습니다.
- 아래 코드를 통해 셀 간의 여백을 주고자 했으나, 셀의 위아래가 잘리는 오류가 발생했습니다. 그래서 현재는 아이템 하나당 섹션을 하나씩 만든 후, 각 섹션에 대한 헤더 높이를 설정하는 방식으로 여백을 줬습니다.
```
override func layoutSubviews() {
    super.layoutSubviews()
    contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 10, left: 0, bottom: 10, right: 0))
}
```

## 👀 참고 사항
https://user-images.githubusercontent.com/51108729/180182054-3253f08c-67c0-4d88-b948-a904712c1012.mov

2022-07-21 11:20 UTC, YebinKim requested changes
알로라 안녕하세요~
테이블뷰를 깔끔한 동작으로 구현하느라 고생 많으셨습니다! 😆👍

제가 이전에 봤던 알람 추천 목록 화면은 "오전/오후" 텍스트와 "알람 숫자" 텍스트가 **수평 방향으로 중앙 정렬** 되어있었던 것으로 기억하는데,
혹시 알람 목록 뷰에서는 **상단 정렬**로 맞춰지는 게 의도된 디자인이 맞을까요?

<img src="https://user-images.githubusercontent.com/38066039/180201213-286879e6-7f33-41f9-b858-a91b81f1358a.png" width="300">

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Network/Models/Alarm.swift
> +
p2;

개행이 2개 들어간 것으로 보이네요! 불필요한 개행이라면 삭제가 필요해보입니다 👀

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +    savedTableView.isScrollEnabled = false
p2;

`viewDidLoad()`에서 너무 많은 책임을 가지고 있는 것으로 보여요!
1. navigationBar 아이템 설정
2. tableView cell 등록
3. tableView delegate/dataSource 등록
4. tableView 기본값 초기화(`presentTableView.isScrollEnabled = false`)

각각 메서드로 분리하면 `viewDidLoad()` 메서드의 역할을 줄일 수 있을 거 같은데 어떻게 생각하실까요?

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm) {
전치사를 활용한 매개변수 네이밍을 사용해서 가독성이 좋네요! 🤩👍

ref: [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#argument-labels)
> When the first argument forms part of a [prepositional phrase](https://en.wikipedia.org/wiki/Adpositional_phrase#Prepositional_phrases), give it an argument label. The argument label should normally begin at the [preposition](https://en.wikipedia.org/wiki/Preposition)

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +    sleepHourField.text = String(Float(alarm.expectedSleepHour/60)) + " 시간"
```suggestion
    sleepHourField.text = String(Float(alarm.expectedSleepHour / 60)) + " 시간"
```

p3;

연산자의 앞뒤로 띄어쓰기를 추가하면 피연산자가 잘 구분되어 보여 가독성이 좋아질 거 같아요~

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +  @IBOutlet weak var savedTableHeight: NSLayoutConstraint!
p3;

`headerHeight` 와 유사한 형식의 네이밍인데 `presentTableHeight`와 `savedTableHeight`는 `NSLayoutConstraint` 타입이고 `headerHeight`는 `CGFloat` 타입이어서 혼동이 생기기 쉬워보여요 🤔
`NSLayoutConstraint` 타입임이 드러나도록 `presentTableHeight`와 `savedTableHeight`의 이름을 정해보면 어떨까요?

2022-07-21 11:20 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +    savedTableView.register(nib, forCellReuseIdentifier: "AlarmListCell")
p4;

`AlarmListCell` 은 여러번 반복되는 문자열이자 클래스의 이름인 것으로 보이네요!
오타 등의 실수를 방지할 수 있도록 문자열을 재사용가능하게 선언해두고 사용해보면 어떨까요?

2022-07-21 12:23 UTC, compuTasha commented
> 알로라 안녕하세요~ 테이블뷰를 깔끔한 동작으로 구현하느라 고생 많으셨습니다! 😆👍
> 
> 제가 이전에 봤던 알람 추천 목록 화면은 "오전/오후" 텍스트와 "알람 숫자" 텍스트가 **수평 방향으로 중앙 정렬** 되어있었던 것으로 기억하는데, 혹시 알람 목록 뷰에서는 **상단 정렬**로 맞춰지는 게 의도된 디자인이 맞을까요?
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/38066039/180201213-286879e6-7f33-41f9-b858-a91b81f1358a.png">

네! 스케치 디자인을 참고하면 상단 정렬로 디자인되어 있습니다!
<img width="328" alt="image" src="https://user-images.githubusercontent.com/51108729/180212321-c62382e7-db38-4557-9ae4-77a06fb37510.png">

2022-07-21 12:44 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +  @IBOutlet weak var savedTableHeight: NSLayoutConstraint!
헉 그렇네요 생각도 못한 부분이에요😲
조금 길더라도 명료함을 위해
`presentTableHeight` 는 `presentTableHeightConstraint`
`savedTableHeight`는 `savedTableHeightConstraint` 로 변경하겠습니다

2022-07-21 12:46 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +  @IBOutlet weak var savedTableHeight: NSLayoutConstraint!
44a0ec08a54c1d407c9fd7506f449d68712ce27e  변경했습니다!

2022-07-21 13:01 UTC, compuTasha commented on Inception/Inception/Network/Models/Alarm.swift
> +
아닛 슬그머니 2개나 들어가있네요 👀
513a6315bd6f61c015a947d4f4003b904fd7b568 수정했습니다!

2022-07-21 13:02 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +    sleepHourField.text = String(Float(alarm.expectedSleepHour/60)) + " 시간"
가독성 팁 기억해두겠습니다!
513a6315bd6f61c015a947d4f4003b904fd7b568 수정했습니다!

2022-07-21 13:05 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm) {
레퍼런스 링크 감사합니다!
참고해서 좀 더 가독성 좋은 코드 짜보겠습니다!!

2022-07-21 13:13 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +    savedTableView.register(nib, forCellReuseIdentifier: "AlarmListCell")
d6286eaeda0671c518b0edfe7594f92db77f5ba0 

`alarmListCellIdentifier` 로 선언해두고 다른 곳에서 사용하도록 수정했습니다!

2022-07-21 13:30 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +    savedTableView.isScrollEnabled = false
이 부분이 너무 뚱뚱해져서 어떻게 해야 할지 고민이었는데 각각 메서드로 정리하면 되는군요!
메서드 네이밍만 좀 더 고민하고 수정하겠습니다!!

2022-07-21 14:19 UTC, chaneeii approved these changes
너무 코드가 깔끔하네요! 

보다가 프로퍼티 선언 순서가 궁금해져 찾은 자료가 있는데 좋아서 공유합니다.

https://github.com/eure/swift-style-guide

요런식으로 선언순서를 정하는게 일반적인것 같네요! 정해진 답은 없지만 좋은 것 같아 공유해봐요🥳
<img width="500" alt="스크린샷 2022-07-21 오후 11 18 53" src="https://user-images.githubusercontent.com/63157395/180236841-4ab87396-da21-4a38-9427-358775c78116.png">

2022-07-21 15:27 UTC, YebinKim approved these changes
알로라~ 리뷰 의견 확인 및 반영 고맙습니다!
고생 많으셨어요 😆👏👍

2022-07-21 23:32 UTC, jinccc97 commented
> > 알로라 안녕하세요~ 테이블뷰를 깔끔한 동작으로 구현하느라 고생 많으셨습니다! 😆👍
> > 제가 이전에 봤던 알람 추천 목록 화면은 "오전/오후" 텍스트와 "알람 숫자" 텍스트가 **수평 방향으로 중앙 정렬** 되어있었던 것으로 기억하는데, 혹시 알람 목록 뷰에서는 **상단 정렬**로 맞춰지는 게 의도된 디자인이 맞을까요?
> > <img alt="" width="300" src="https://user-images.githubusercontent.com/38066039/180201213-286879e6-7f33-41f9-b858-a91b81f1358a.png">
> 
> 네! 스케치 디자인을 참고하면 상단 정렬로 디자인되어 있습니다! <img alt="image" width="328" src="https://user-images.githubusercontent.com/51108729/180212321-c62382e7-db38-4557-9ae4-77a06fb37510.png">

옷..이부분은 논의가 필요할 듯 합니다!

2022-07-21 23:34 UTC, jinccc97 approved these changes
수고많으셨습니다! 👍

2022-07-22 00:18 UTC, taehyeonk approved these changes
고생하셨습니다~👍👍👍

2022-07-22 06:16 UTC, pppaper approved these changes
코드가 정말 깔끔해요~ 고생하셨습니다👍👍

2022-07-25 00:21 UTC, compuTasha commented
> 너무 코드가 깔끔하네요!
> 
> 보다가 프로퍼티 선언 순서가 궁금해져 찾은 자료가 있는데 좋아서 공유합니다.
> 
> https://github.com/eure/swift-style-guide
> 
> 요런식으로 선언순서를 정하는게 일반적인것 같네요! 정해진 답은 없지만 좋은 것 같아 공유해봐요🥳 <img alt="스크린샷 2022-07-21 오후 11 18 53" width="500" src="https://user-images.githubusercontent.com/63157395/180236841-4ab87396-da21-4a38-9427-358775c78116.png">

이런 것도 있군요..!👀
참고하겠습니다 감사합니다!

2022-07-25 01:26 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
> +    savedTableView.isScrollEnabled = false
943218e1451e80010ae33c3de2d64b2965261c41 수정했습니다!

2022-07-25 01:26 UTC, merged