✨ feat : Core Data 연동, 데이터 저장 및 불러오기 #21
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #31
Opened 2022-07-21 10:05 UTC by jinccc97

## 👀 관련 이슈
#21

## 👀 구현/변경 사항
- CoreData Entity를 생성하고 이를 관리할 subClass 를 생성했습니다.
- 다른 뷰에서 쉽게 저장, 삭제 등 처리할 수 있도록 manager 파일을 따로 빼두었습니다. 이런식으로 사용하면 됩니다.
<img width="784" alt="스크린샷 2022-07-21 오후 6 48 36" src="https://user-images.githubusercontent.com/61951603/180184649-3ac2f74f-0076-4006-af3e-96a447ca1dc2.png">

## 👀 PR Point
- 이번에도 초반에 무지성 commit 때문에 **처음 2개 커밋은 무시**해주셔도 될 것 같습니다.. 죄송합니다 유의하겠습니다.
- 수면 기록에 있는 쓰레기통, + 버튼은 테스트용이고 추후 계속 테스트를 할 수도 있는 상황이 있을 듯하여 남긴채로 커밋합니다. 나중에 삭제하도록 하겠습니다.
![image](https://user-images.githubusercontent.com/61951603/180188295-4116ba74-46ac-4a96-9107-7c36cb8ca33e.png)
- 현재 이런 구조인데요, 맞는지는 모르겠습니다..

## 👀 참고 사항
[참고: CoreData로 데이터 저장 및 관리하기](https://hanulyun.medium.com/swift-coredata%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%80%EC%9E%A5-%EB%B0%8F-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0-19f61c95232f)

2022-07-21 11:50 UTC, YebinKim requested changes
밀리 안녕하세요~
레퍼런스를 활용해서 CoreData 사용에 편리하도록 manager 타입을 만들고,
메서드가 한 번에 너무 많은 일을 하지 않도록 잘 분리해서 작성해주신 점이 눈에 띄었습니다!! 😆👍

고생 많으셨어요 👏👏

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Global/CoreData/SleepTrackDataManger.swift
> +  private func deleteItem(_ sleepRecord: SleepRecordItem) {
질문;

다른 메서드와 달리 **단일 아이템 delete 메서드**만 private 으로 사용된 이유가 무엇일까요?

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Global/Extension/Date/Date+.swift
> +    dateFormatter.dateFormat = "MM.dd"
질문;

이번 이슈에 포함되어야 할 변경 사항이 맞을까요??
[✨ feat : 수면 기록 coredata 저장 및 불러오기](https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/pull/31/commits/a09941beea587fbce48bb49dfe525f84fb815b56) 커밋에 올라온 것으로 보이는데, 내용 상 관련 없는 내용으로 보여서 질문드립니다! 🤔

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Network/Models/SleepRecord.swift
> +  init(sleepSatisfacation: SleepSatisfacation, bedtimeDate: Date, wakeuptimeDate: Date){
```suggestion
  init(sleepSatisfacation: SleepSatisfacation, bedtimeDate: Date, wakeuptimeDate: Date) {
```

p3;

소괄호와 중괄호 사이 띄어쓰기가 하나 빠진 거 같아요~

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +    saveNewItem(sleepRecordItem: SleepRecord(sleepSatisfacation: SleepSatisfacation.good, bedtimeDate: Date.now.addingTimeInterval(-60*60*6.5), wakeuptimeDate: Date.now))
```suggestion
    let sleepRecordItem = SleepRecord(sleepSatisfacation: SleepSatisfacation.good, 
                                      bedtimeDate: Date.now.addingTimeInterval(-60 * 60 * 6.5)
    saveNewItem(sleepRecordItem: sleepRecordItem, wakeuptimeDate: Date.now))
```

p3;

연산자 사이에 띄어쓰기가 추가되면 피연산자가 잘 구분돼서 가독성이 좋아질 거 같아요!
혹시 띄어쓰기를 추가하는 것에 대해 어떻게 생각하실까요? 👀

또한, 라인이 많이 길어져서 `SleepRecord` 인스턴스 생성 코드를 별도의 선언으로 분리하고 개행을 추가해주면 한눈에 들어오기 쉬울 거 같아요~

그리고 `-60 * 60 * 6.5` 의 숫자가 무엇을 의미하는지 알 수 없는 숫자라(이런걸 매직넘버라고 합니다)
별도의 상수로 선언해주면 코드를 이해하는 데 도움될 거 같습니다!

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
> +  func update(with dailySleepRecord: SleepRecordItem) {
전치사를 활용한 매개변수 네이밍을 사용해서 잘 읽히네요!! 🤩👍

ref: [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#argument-labels)
> When the first argument forms part of a [prepositional phrase](https://en.wikipedia.org/wiki/Adpositional_phrase#Prepositional_phrases), give it an argument label. The argument label should normally begin at the [preposition](https://en.wikipedia.org/wiki/Preposition)

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +  private func getAllItems() {
p3;

Swift 는 반환받는 값이 이름에서 명확하게 드러날 경우 get~ 네이밍을 지양하고 있습니다.
또한, 값을 반환하기 보다는 `dailySleepRecords`의 값을 업데이트하고 `tableView`를 reload 하는 역할을 수행하는 메서드인 것으로 보이는데 👀
**fetch** 또는 **reload** 네이밍을 활용해보면 어떨까요?

2022-07-21 11:50 UTC, YebinKim commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
>    override func viewDidLoad() {
p2;

프로퍼티와 메서드 사이에 개행이 하나 누락된걸까요? 🤔

2022-07-21 13:06 UTC, chaneeii approved these changes
제가 코어데이터에 대해서 잘 몰라서 제대로된 리뷰를 하지못한것 같네요ㅠ
고생많았습니다 밀리!

2022-07-21 13:06 UTC, chaneeii commented on Inception/Inception/Global/CoreData/SleepRecordItem+CoreDataProperties.swift
> +}
요부분 따로 extension 으로 빼둔 이유가 궁금합니다!

2022-07-21 13:06 UTC, chaneeii commented on Inception/Inception/Global/Extension/Date/Date+.swift
> +    dateFormatter.dateFormat = "MM.dd"
date+ extension 쪽은 제가 MM 과 mm 을 잘못 작성하여 밀리가 이쪽부분을 우선 사용하기 위해 코드를 추가했습니다 😭
제가 따로 PR 을 날리려고 했는데 시간이 지금에서야 되었네요! 미안해요 밀리 ㅠ

2022-07-21 23:38 UTC, jinccc97 commented on Inception/Inception/Global/CoreData/SleepTrackDataManger.swift
> +  private func deleteItem(_ sleepRecord: SleepRecordItem) {
아 처음엔 deleteAllItem 메서드만 구현하려고 했어서 deleteItem이 deleteAllItem 내에서 돌아가게 하려고 했었습니다!
하지만 밖에서도 deleteItem 이 필요할 것 같아서 수정했었는데 private 지우는걸 까먹었네요..! private 삭제하도록 하겠습니다!

2022-07-21 23:39 UTC, jinccc97 commented on Inception/Inception/Global/Extension/Date/Date+.swift
> +    dateFormatter.dateFormat = "MM.dd"
아이쿠 저걸 안올라가게 하려고 신경썼는데 어쩌다보니 올라갔나봅니다..! 혼란드려 죄송합니다😭

2022-07-21 23:45 UTC, jinccc97 commented on Inception/Inception/Global/CoreData/SleepRecordItem+CoreDataProperties.swift
> +}
코어데이터 구조 생성 시 자동으로 생성되는 extension 이에요! 저도 이유는 잘 모르겠습니다..!

2022-07-21 23:59 UTC, jinccc97 commented on Inception/Inception/Network/Models/SleepRecord.swift
> +  init(sleepSatisfacation: SleepSatisfacation, bedtimeDate: Date, wakeuptimeDate: Date){
8a4f3a1ab8aaf8ae477579139be3888f7b0fc8ed
오 매의눈...! 수정했습니다!

2022-07-22 00:00 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +  private func getAllItems() {
오.. 그렇군요! 기억해둘게요. 확실히 getAllItem보다는 fetch가 더 잘 어울리는 이름같네요! 수정하도록 하겠습니다.
4a03569b863e77a4512be4f8d4f15dd9fce874b8

2022-07-22 00:00 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
>    override func viewDidLoad() {
매의눈22222222... 수정하겠습니다!
881e7dea0cc7ba69c6bc8dc67ea8fc0b0ffd5407

2022-07-22 00:03 UTC, jinccc97 commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +    saveNewItem(sleepRecordItem: SleepRecord(sleepSatisfacation: SleepSatisfacation.good, bedtimeDate: Date.now.addingTimeInterval(-60*60*6.5), wakeuptimeDate: Date.now))
- 오 확실히 전보다 시원한 느낌이 듭니다!! 연산자에도 공백 추가..메모...

- **별도의 선언으로 분리** 라는 것이 이렇게 따로 상수를 만드는 것이 맞을까요? 😭

- 앗 보는 사람에 대한 배려가 부족했습니다.. 따로 상수로 빼서 이름을 붙여주겠습니다!

967b45eadbd2a491285d74fbd9c3654ebb24bafc

2022-07-22 00:04 UTC, jinccc97 commented on Inception/Inception/Global/CoreData/SleepTrackDataManger.swift
> +  private func deleteItem(_ sleepRecord: SleepRecordItem) {
7da801a0253d912dbd366b7c69df5c75093b7de8

2022-07-22 00:09 UTC, chaneeii commented on Inception/Inception/Global/CoreData/SleepRecordItem+CoreDataProperties.swift
> +}
나중에 저 아이템으로 뭔가 하라는것같은데 한번 코어데이터 공부를 해봐야겠네요 !! 🔥

2022-07-22 01:29 UTC, YebinKim commented on Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
> +    saveNewItem(sleepRecordItem: SleepRecord(sleepSatisfacation: SleepSatisfacation.good, bedtimeDate: Date.now.addingTimeInterval(-60*60*6.5), wakeuptimeDate: Date.now))
**별도의 선언으로 분리** 에 대해 생각했던 코드는 https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/967b45eadbd2a491285d74fbd9c3654ebb24bafc 에 작성된 코드와 같은 내용이었습니다~
추가로 `testAtualSleepTime`에 타입 어노테이션을 추가해주면 타입추정을 줄일 수 있어 컴파일 성능 향상에 도움될 거 같아요!

2022-07-22 01:31 UTC, YebinKim approved these changes
밀리~ 리뷰 코멘트 확인 및 반영 고맙습니다!
고생 많으셨어요 ☺️👍

(그리고 머지 전 컨플릭 해결이 필요해보여요)

2022-07-22 06:05 UTC, chaneeii reviewed
CRUD 관련하여 새로 메소드 명을 바꾼 내용에 대하여 추가 커멘트남겨봅니다!

2022-07-22 06:05 UTC, chaneeii commented on Inception/Inception/Global/CoreData/AlarmDataManager.swift
> +    var models: [AlarmItem] = [AlarmItem]()
p2; 

오늘 아마 task 를 나눌때 CRUD 라는 단어를 사용해서 @jinccc97 가 이걸로 메소드 명을 설정해야겠구나 라고 하고 요렇게 바꿔준것같은데 CRUD 는 operation을 표현하는 단어라서 사실 뭔가 이런데 쓰기에는 애매한것같아요!

read 말고 원래대로 fetch(), fetchAlarmItems() 처럼 좀 더 직관적인 표현을 써도 좋을 것 같아요! 어떠한 역할을 하는지 잘 알수있는..?
특히, 밀리의 말대로 코어데이터는 DB가 아니라 프레임워크라서..!

이게 느낌적인거라 뭔가 설명하기가 어렵네요ㅠ 이해가 안간다면 다시 한번 물어봐주세요!

2022-07-22 06:05 UTC, chaneeii commented on Inception/Inception/Global/CoreData/SleepTrackDataManger.swift
> +  func read() -> [SleepRecordItem] {
요쪽도 crud 관련 메소드명 한번 같이 고민해봐요 🥺

2022-07-22 06:11 UTC, pppaper approved these changes
멋져요 밀리!!!👍

2022-07-22 06:11 UTC, pppaper commented on Inception/Inception/Global/CoreData/AlarmDataManager.swift
> +class AlarmDataManger {
여기부분 혹시 manager오타인가요..? 👀

2022-07-25 01:18 UTC, tea-hkim approved these changes
작업량이 많아 보이네요 ㄷㄷ 수고 많으셨습니다 :)

2022-07-25 08:46 UTC, jinccc97 commented on Inception/Inception/Global/CoreData/AlarmDataManager.swift
> +class AlarmDataManger {
수정했습니다!
a5988d9be2a5bc277a6802ea5c24feecf3fb10c0

2022-07-25 08:46 UTC, jinccc97 commented on Inception/Inception/Global/CoreData/AlarmDataManager.swift
> +    var models: [AlarmItem] = [AlarmItem]()
좀 더 직관적으로 변경했습니다!
73ef32cde9ecec2e91af68585fd740d6755f7e28

2022-07-25 08:48 UTC, merged