🐛 fix : AlarmListCell UI 수정 #35
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #38
Opened 2022-07-26 00:34 UTC by chaneeii

## 👀 관련 이슈

Closes #35 

## 👀 구현/변경 사항

1. 알람리스트셀 UI constraints 수정 (가운데 정렬)
2. 알람리스트 현재알람만 활성화되도록 변경 

## 👀 PR Point

2.  **_알람리스트 현재 알람만 활성화되도록 변경하는 것은 알로라 파트에서 쉽게 변경가능하여 알로라가 기존에 따로 작업을 해두었다고 합니다😥 따라서 merge 할때 이부분살리는 방향으로 merge 하도록 하겠습니다._** => 해당파일빼고 코드리뷰 바랍니다!
 ( 같은 파트에 있는 분들은 동일작업을 두번하지 않도록 작업영역을 서로 업데이트 하는게 중요해보이네요...😥 )
-  78d2ebd027d8b12a5db62b71af142b080ca6fac5 
-  https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/issues/35#issuecomment-1194394904

## 👀 참고 사항

<img width="993" alt="스크린샷 2022-07-26 오전 9 24 07" src="https://user-images.githubusercontent.com/63157395/180897236-3098a3d8-6e4f-48d0-992c-2f6c5158da50.png">

2022-07-26 00:49 UTC, taehyeonk approved these changes

2022-07-26 01:24 UTC, tea-hkim approved these changes
코드 베이스로 작업하시는게 능숙해지는 것 같습니다 :)

2022-07-26 01:32 UTC, compuTasha requested changes
특히 auto layout 관련해서
테이블 스와이프 삭제 기능이랑 함께 확인해야 할 것 같은데
관련 기능 merge 이후에 적용해보고 merge하는 건 어떨까요?!

2022-07-26 01:32 UTC, compuTasha commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmList;
p2;

앗 요 친구가 같이 들어왔네요👀
이 부분 다시 Main 으로 돌려두고 커밋해야 할 것 같아요!

2022-07-26 03:01 UTC, pppaper approved these changes
멋져요~~ 짱짱!!!

2022-07-26 03:19 UTC, jinccc97 requested changes
수고하셨습니다!!

2022-07-26 03:19 UTC, jinccc97 commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmList;
앗 스토리보드가 Main이 아닌데 혹시 의도하신건가요!!

2022-07-26 03:45 UTC, YebinKim approved these changes
커밋도 코드도 깔끔하네요~!
고생 많으셨어요 😆👏

2022-07-26 03:45 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
>        if presentAlarm != nil {
p2;

`Comparing non-optional value of type 'Alarm' to 'nil' always returns true` 워닝이 발생하고 있네요 ⚠️
워닝 제거가 필요할 거 같습니다!

또한, 현재는 임시 데이터를 쓰고 있어서 전역변수로 선언해둔 것으로 생각했는데
이후 실제 데이터를 저장할 때는 전역변수와는 다른 방식으로 데이터 관리가 필요해보여요~

2022-07-26 03:45 UTC, YebinKim commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm, isSetAlarm: Bool) {
```suggestion
  func alarmCellUpdate(with alarm: Alarm, isSet: Bool) {
```
p4;

매개변수 이름 추천드립니다~
`isSet` 또는 `isOn` 으로 작성해도 의미 전달이 잘 될 거 같아요!

2022-07-26 12:00 UTC, chaneeii commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
>        if presentAlarm != nil {
비비 피드백 감사합니다 :) 이 부분 기존/현 작업자가 알로라라서 상의후에 수정결정하도록 하겠습니다 ☺️
@compuTasha  앗! 알로라 요부분을 제가 건드려도될까요?

2022-07-26 12:01 UTC, chaneeii commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm, isSetAlarm: Bool) {
이 부분도 기존/현 작업자가 알로라라서 상의후에 수정결정하도록 하겠습니다 
@compuTasha  알로라 요부분도 제가 건드려도될까요?

2022-07-27 01:16 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
>        if presentAlarm != nil {
앗 이 부분은 현재 값이 있는 더미 데이터랑 비교해서 생기는 문제인 것 같습니다!
추후 코어데이터와 연결하는 과정에서는 워닝이 사라질 것 같아요!

2022-07-27 01:19 UTC, compuTasha commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm, isSetAlarm: Bool) {
현재 `AlarmListViewController` 에서 저장된 알람 목록 cell에 opacity를 주고 있어서
setSelected를 포함한 isSet 부분을 삭제해도 될 것 같습니다..!!

2022-07-27 02:41 UTC, chaneeii commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmList;
반영이요✨
e520d4c0eb681d9f9e08c9669a9e6b79afd5fb12

2022-07-27 02:42 UTC, chaneeii commented on Inception/Inception.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UIMainStoryboardFile = AlarmList;
✨ 반영완료!
e520d4c0eb681d9f9e08c9669a9e6b79afd5fb12

2022-07-27 02:42 UTC, chaneeii commented on Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
> +  func alarmCellUpdate(with alarm: Alarm, isSetAlarm: Bool) {
넵 변경했습니다 2886bea8c33a896b36140f32f8ae3b615943f3ea

2022-07-27 02:43 UTC, compuTasha approved these changes

2022-07-27 02:44 UTC, compuTasha approved these changes
사이 좋아진 취침, 알람 시간 너무 좋아요
수고하셨습니다!!! 👍🎉

@jinccc97 뮐리도 체크하시고 어프루브 부탁드려용

2022-07-27 02:47 UTC, merged