Feat/20 search alarm
DeveloperAcademy-POSTECH/MC3-Team13-Inception pull request #41
Opened 2022-07-26 03:03 UTC by taehyeonk

## 👀 관련 이슈
#20 

## 👀 구현/변경 사항
- 시간 설정하는 상단 구역 레이아웃 구현
- 각각의 셀 취합 하면서 디자인한 것과 동일하게 구현
- '알람 찾기' 버튼 클릭 시 추천 알람 표시
- DatePicker로 시간 설정 시 설정한 시간으로 알람 찾기 가능
- 추천 알람에서 '추가' 버튼 클릭 시 Alert 구현

<p>
<img width="190" alt="image" src="https://user-images.githubusercontent.com/29690062/180909615-4a8eee60-6f18-4183-82b5-1ed28171ad3b.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/29690062/180909637-44681f1f-04e7-4135-b5b9-82dd80cb7713.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/29690062/180909731-d3f86c8c-e50d-4549-a7e0-70592896e8e7.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/29690062/180909668-3d059669-2aa4-46f9-9ab8-488551e362a5.png">
</p>

## 👀 PR Point
**Design**
- 시간 설정 하는 영역의 경우 Cell이 아닌 View를 TableView 안에 추가하는 방식으로 해결  
- 디자인 설정은 Storyboard 내에서 User Defined Runtime Attributes에서 다음과 같이 설정  
<img width="200" alt="image" src="https://user-images.githubusercontent.com/29690062/180912333-beaec6f1-8cf3-44e7-ba29-2e04ab990187.png">
- Cell 디자인의 경우 Cell 내의 ContentView에 속성값 조절로 구현 (padding을 주기 위해 ContentView 사이즈를 더 주는 방식) (도움을 주신@YebinKim에게 무한한 감사를..)

``` swift
// SleepBasedRecoCell.swift
  override func layoutSubviews() {
    super.layoutSubviews()
    
    contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0))
    contentView.layer.cornerRadius = 11
  }
```
(이 부분 init 함수로 처리하고 싶었는데, 수 많은 오류에 부딪혀 수정하지 못했습니다..ㅠㅠ @YebinKim)

``` swift
// SleepBasedViewController.swift
extension AwakeBasedViewController: UITableViewDelegate {
  func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
    return 120 + 16 // cell size: 120, top padding: 8, bottom padding: 8
  }
}
```

**Alert**
Alert의 경우
`UIApplication.shared.keyWindow?.rootViewController?.present(alert, animated: true, completion: nil)`
를 사용해서 UITableViewCell 내에서 호출하는 방식으로 구현

## 👀 참고 사항
- 추천 알람 Cell 목데이터로 처리해둔 상황이라 나중에 데이터를 받아와서 하는 것으로 수정해야함 (현재 3개지만 4개를 추천하는 걸로 구현 필요)
- Alert 구현되어 있지만 '변경하기' 버튼 클릭 시 후처리 동작 구현 해야함

2022-07-26 03:29 UTC, compuTasha requested changes
cell 파일명이 ~~RecoCell 로 끝나는데 혹시 어떤 의미일까요..?

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.xib
> +                <color key="backgroundColor" red="0.10980392156862745" green="0.10980392156862745" blue="0.11764705882352941" alpha="1" colorSpace="calibratedRGB"/>
p2;

셀 배경색을 테이블 셀 디폴트 색상인 `secondarySystemGroupedBackgroundColor` 로 변경하는 건 어떨까요
editing mode 같은 상호작용에서도 훨씬 자연스러워서 제안드립니다..!😮

기존 커스텀 색상
<img width="336" alt="image" src="https://user-images.githubusercontent.com/51108729/180840587-2c25f380-0af2-4ebf-9800-3d1682771248.png">
`secondarySystemGroupedBackgroundColor` 색상
<img width="344" alt="image" src="https://user-images.githubusercontent.com/51108729/180840688-b33578f1-e780-4b10-9e5f-b3abedec93f1.png">

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
p4;

data.isEmpty 와 같이 isEmpty 함수 말고 
따로 변수를 만들어 사용하신 이유가 있을까요??

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +      print("tanny log--> 변경하기 동작")
p3;

여기도 액션이 제대로 동작하는지 확인하는 로그가 함께 커밋된 것 같아요..!

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +    let alert = UIAlertController(title: "현재 알람으로 설정할까요?", message: "한 번에 하나의 알람만 세팅할 수 있어요\n새 알람을 활성화할까요?", preferredStyle: UIAlertController.Style.alert)
p3;

마찬가지로 가독성을 위해 줄바꿈이 필요해 보입니다..! 👀

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    let alert = UIAlertController(title: "현재 알람으로 설정할까요?", message: "한 번에 하나의 알람만 세팅할 수 있어요\n새 알람을 활성화할까요?", preferredStyle: UIAlertController.Style.alert)
p3;

가독성을 위해 줄바꿈이 필요해 보입니다..!

2022-07-26 03:29 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +      print("tanny log--> 변경하기 동작")
p3;

액션이 제대로 동작하는지 확인하는 로그가 함께 커밋된 것 같아요!
이 부분은 삭제하는 게 어떨까요..?!

2022-07-26 03:40 UTC, jinccc97 approved these changes
수고하셨습니다!

2022-07-26 03:40 UTC, jinccc97 commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var data = [AlarmTime(sleepHour: "7.5 시간", bedTime: "오후 11:00", wakeupTime: "오전 08:00"),
p3;
이 더미 데이터는 삭제해도 괜찮지 않을까요?

2022-07-26 03:41 UTC, pppaper approved these changes
멋집니다~~ 태니 짱~!!!!👍

2022-07-26 03:42 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
아 사실 isEmpty가 data가 비어있단 의미는 아니었고, 첫 화면에 Empty 화면을 출력해야되는 경우를 Boolen으로 구분해서 조건문으로 cell을 출력하도록 만들기 위한 변수 선언이었습니다!

2022-07-26 03:52 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
그렇다면 isEmpty 변수 대신
처음에는 테이블뷰를 .isHidden = true을 통해 숨겨두고
필요한 경우에 .isHidden = false로 표시하는 건 어떨까요?!
isEmpty 변수의 의미가 모호한 것 같아 제안드립니다..!

2022-07-26 03:56 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0))
비비의 꿀팁 저도 줍줍해갑니다.. 🍯🐝

2022-07-26 11:58 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0))
이게 UI의 경우 고정되니까 매번 호출되게 layoutSubviews()에서 동작하도록 하지 말고 init 함수를 사용해서 지정해주면 좋을 것 같다고 해주셨는데, 오류와 부딪혀 해결하지 못했습니다;;

2022-07-26 12:01 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +      print("tanny log--> 변경하기 동작")
앗 수정했습니다(359b592d3a53b86d5f23b9c3888b6e5a665728fc)

2022-07-26 12:02 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +      print("tanny log--> 변경하기 동작")
수정 했습니다 (359b592d3a53b86d5f23b9c3888b6e5a665728fc)

2022-07-26 12:03 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +    let alert = UIAlertController(title: "현재 알람으로 설정할까요?", message: "한 번에 하나의 알람만 세팅할 수 있어요\n새 알람을 활성화할까요?", preferredStyle: UIAlertController.Style.alert)
수정 했습니다 (1d7eb8d048140b39d9cb77c813d35655964af7ae)

2022-07-26 12:03 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    let alert = UIAlertController(title: "현재 알람으로 설정할까요?", message: "한 번에 하나의 알람만 세팅할 수 있어요\n새 알람을 활성화할까요?", preferredStyle: UIAlertController.Style.alert)
수정 했습니다 (1d7eb8d048140b39d9cb77c813d35655964af7ae)

2022-07-26 12:13 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var data = [AlarmTime(sleepHour: "7.5 시간", bedTime: "오후 11:00", wakeupTime: "오전 08:00"),
아 지금은 표시하는 것을 목데이터로 해놓았기 때문에 저게 없으면 동작 자체를 안하는 구조이긴 합니다만..
생각해보니 저는 저장된 데이터를 불러올 것도 아니니까 다른 방식으로 구현해야겠군요!
picker 시간 기준 지정된 네 가지 시간을 생성해서 불러오는 방식으로 함수화 해봐야겠습니다.

2022-07-26 12:35 UTC, chaneeii requested changes
고생많았습니다 🔥

2022-07-26 12:35 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +    data[2].bedTime = formatter.string(from: setTime+16200)
p4

요부분은 나중에 merge 하고 date 관련 extension 활용해서 변경부탁드려요!
또한 미래의 재사용성을 위해 for문을 활용해도 좋지않을까요? 5400 분 단위로 증가하고 있어서 for문을 돌릴수있어보여요...!

2022-07-26 12:35 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +      // MARK: - '변경하기' 버튼 Action
TODO: 도 생각나면 사용해주세요 😇 (영업중)

p3 ) 
그리고 cancel - confirm 이 뭔가 더 짝이 맞는것같습니다! addAction 이라는 단어뒤에 ok"Action" 이 한번더 있어서 머랄까 한국어로하면 아래 감성인느낌이네요! 

현재->> 변경추천
동작추가 : 취소하기 ->> 동작추가 : 취소하기
동작추가 : 맞음동작 ->> 동작추가 : 확인하기

2022-07-26 12:35 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
p2
요부분이 현재는 UI보여주기식으로 넣은 데이터 같아보이네요! 
삭제하거나 나중에 삭제할수있도록 알리는 주석처리하는 것이 좋아보여요!

2022-07-26 12:35 UTC, chaneeii commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +      return data.count
p2
이부분은 저희가 기상시간기준 취침시간을 보여줄때 단순히 정해진 데이터의 개수가 아니라 가능한 시간대, 현재 취침시간 이후로만 취침시간 추천해주기로해서 해당부분에 다른 로직을 적용해야할것으로 보이네요!

이번PR 에서 계산하기 로직이 따로 적용되지 않아서 아마 따로 없는거겠죠...?

2022-07-26 13:12 UTC, tea-hkim approved these changes
여기도 코드의 양이 엄청나네요... 고생하셨습니다! 다른 분들이 리뷰를 다 하셔서 저는 이만

2022-07-26 13:38 UTC, compuTasha requested changes

2022-07-26 13:38 UTC, compuTasha commented on Inception/Inception/Info.plist
> +					<string>AlarmCalculator</string>
p3; 

이 친구가 또 따라왔어요..!! 👀

2022-07-27 01:16 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
저의 경우에는 tableView 안에 View가 있어서 '알람 찾기' 버튼을 누르지 않은 첫 실행을 구분하기 위한 bool값 이었습니다.
변수명을 우선 변경해 두었고, 나중에 목데이터를 삭제하고 새롭게 생성해서 작업할 때는 또 코드가 변경될 수 있을 것 같네요! (0ca70895c05dd43239d16b9624a7c5f14f1da174)

2022-07-27 01:53 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +      // MARK: - '변경하기' 버튼 Action
그러네요
수정했습니다. 훨씬 더 좋은거 같아요 (da327fb6caeaa264de7ad0aa3e298e5f59207527)

2022-07-27 01:55 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +      return data.count
아직 로직을 적용하지 않은 것이 맞아요.
그런데 로직을 만들더라도 해당 내용은 그대로 유지될 것 같다는 생각이었습니다.
저 부분은 '알람 찾기' 버튼을 누르지 않은 초기실행과 구분하기 위한 것이어서 배열을 새롭게 생성하는 것이 아니면 그대로 쓰면 될 것 같아요!

2022-07-27 02:13 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.xib
> +                <color key="backgroundColor" red="0.10980392156862745" green="0.10980392156862745" blue="0.11764705882352941" alpha="1" colorSpace="calibratedRGB"/>
수정 했습니다(6eaefbe29ba2af189169c997cecf221756e6aa23)

2022-07-27 02:38 UTC, compuTasha commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
-> alarm 데이터 모델 사용해서 변경 예정

2022-07-27 03:49 UTC, YebinKim requested changes
태니 안녕하세요~
테이블뷰 구현이 쉽지 않았을텐데 깔끔한 동작으로 구현하느라 고생 많으셨어요 😆👍👏

코멘트가 많지는 않은데 현재 워닝이 뜨는 부분이 있어서 Request Changes 로 요청드렸습니다!

2022-07-27 03:49 UTC, YebinKim commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +  var setTime = Date()
p2;

타입 내부에서만 사용되는 프로퍼티일까요?
만약 그렇다면 `private` 으로 선언될 필요가 있을 거 같아요!

2022-07-27 03:49 UTC, YebinKim commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    UIApplication.shared.keyWindow?.rootViewController?.present(alert, animated: true, completion: nil)
p2;

`'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes` 워닝이 발생하고 있습니다 ⚠️
수정이 필요해보여요!

2022-07-27 03:49 UTC, YebinKim commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +    contentView.layer.cornerRadius = 11
p2;

`layoutSubviews()` 가 호출될 때마다 라운딩 처리가 되어야 할 필요가 있을까요? 🤔

2022-07-27 03:49 UTC, YebinKim commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    data[2].wakeupTime = formatter.string(from: setTime+16200)
```suggestion
    data[0].wakeupTime = formatter.string(from: setTime + 27000)
    data[1].wakeupTime = formatter.string(from: setTime + 21600)
    data[2].wakeupTime = formatter.string(from: setTime + 16200)
```

p4;

연산자와 피연산자 사이에 띄어쓰기를 추가하면 훨씬 읽기 쉬워질 거 같아요~ 👀

2022-07-27 12:44 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var isEmpty = true
논의한 대로 수정했습니다!! (2193bc743c3599d18f659d92da570f14b0ae4500)
Alarm 데이터 모델을 사용하는 빈 리스트를 선언해서 append한 뒤에 뿌려주는 형식으로 구현했고, 자연스럽게 isEmpty를 체크할 필요 없이 Cell이 생성되는 만큼만 보여주도록 구현했습니다.

2022-07-27 12:45 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +  var data = [AlarmTime(sleepHour: "7.5 시간", bedTime: "오후 11:00", wakeupTime: "오전 08:00"),
더미 데이터 없이 Alarm 데이터 모델을 사용하는 방식으로 수정했습니다! (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-27 12:46 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +    data[2].bedTime = formatter.string(from: setTime+16200)
Alarm 데이터 모델을 사용했고, for문도 적용해봤습니다. (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-27 12:46 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
마찬가지로 삭제 후 Alarm 데이터 모델을 사용해서 구현했습니다! (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-27 12:47 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
> +      return data.count
초기실행 구분 없이 Alarm 데이터 모델을 가져와서 빈 리스트 배열에 append 하고 count 만큼 출력하는 방식으로 개선했습니다. (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-27 12:48 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +  var setTime = Date()
Alarm 데이터 모델을 활용해서 구현하는 과정에서 private 선언으로 수정했습니다! (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-28 01:10 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    UIApplication.shared.keyWindow?.rootViewController?.present(alert, animated: true, completion: nil)
처음에 방법을 몰라서 그대로 두었는데, 다시 보니 어찌어찌 해결했습니다! (9f41ad0716562d9da86f2074d513483a14cbe9b1)

2022-07-28 01:11 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
> +    data[2].wakeupTime = formatter.string(from: setTime+16200)
Alarm 데이터 모델에 맞게 수정하면서 전면 수정했습니다! (2193bc743c3599d18f659d92da570f14b0ae4500)

2022-07-28 01:14 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
> +    UIApplication.shared.keyWindow?.rootViewController?.present(alert, animated: true, completion: nil)
https://techhelpnotes.com/swift-xcode-warning-windows-was-deprecated-in-ios-15-0-use-uiwindowscene-windows-on-a-relevant-window-scene-instead/
해당 내용 참고했습니다.

2022-07-28 01:54 UTC, taehyeonk commented on Inception/Inception/Info.plist
> +					<string>AlarmCalculator</string>
아앗.. 확인.. (2cce48c62048d7c8fe5bc58d5253d94be961427b)

2022-07-28 01:55 UTC, chaneeii approved these changes

2022-07-28 02:09 UTC, YebinKim approved these changes
p1~p2 로 드린 코멘트는 추후 리팩토링으로 개선해도 충분할 거 같습니다!
고생 많으셨어요~

2022-07-28 02:14 UTC, taehyeonk commented on Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
> +    contentView.layer.cornerRadius = 11
우선은 init을 제대로 이해하지 못해서인지 init함수를 사용하는 방식으로 해결하지 못했고,
스토리보드에서 설정하는 방식으로 처리해봤습니다! (8a2649c73ec76b5ffa7a3cc473203a99dceae19b)

2022-07-28 02:17 UTC, taehyeonk commented
> p1~p2 로 드린 코멘트는 추후 리팩토링으로 개선해도 충분할 거 같습니다! 고생 많으셨어요~

@YebinKim 
우선은 init을 제대로 이해하지 못해서인지 init함수를 사용하는 방식으로 해결하지 못했고,
스토리보드에서 설정하는 방식으로 처리해봤습니다! (https://github.com/DeveloperAcademy-POSTECH/MC3-Team13-Inception/commit/8a2649c73ec76b5ffa7a3cc473203a99dceae19b)

2022-07-28 02:20 UTC, compuTasha approved these changes
수고하셨습니다!!🔥

2022-07-28 03:16 UTC, merged